apiVersion: v1
kind: Secret
metadata:
  name: hackathon-autenticacao-secret
type: Opaque
data:
  MONGO_CONNECTION_STRING: bW9uZ29kYjovL2ZpYXA6ZmlhcDEyMzQ1NkBzZXJ2aWNlLW1vbmdvLWRiOjI3MDE3L2FkbWlu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-autenticacao
  labels:
    app: hackathon-autenticacao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon-autenticacao
  template:
    metadata:
      labels:
        app: hackathon-autenticacao
    spec:
      containers:
        - name: container-hackathon-autenticacao
          image: lruizd/techchallenge-dotnet-contactintegration:latest
          ports:
            - containerPort: 5010         
          env:
            - name: MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: hackathon-autenticacao-secret
                  key: MONGO_CONNECTION_STRING            
            - name: ASPNETCORE_ENVIRONMENT
              value: "Kubernetes"
---
apiVersion: v1
kind: Service
metadata:
  name: service-hackathon-autenticacao
  labels:
    app: hackathon-autenticacao
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5010
      nodePort: 31000
  selector:
    app: hackathon-autenticacao